owo-colors/owo-colors

src/dyn_styles.rs

Prior to this commit whenever a `Default` style is used it will always emit the original text followed by what I can only assume is the "clear ansi flags" code. This PR changes the `Display` impl for `Style` to instead check if any codes were already emitted and skips the closing code if none were.

omit closing ansi code if no open codes were emitted

---

Cargo.toml
examples/is_tty.rs
src/dyn_styles.rs
src/lib.rs
src/tty_display.rs

Also bumping to 1.3.0
Example from the docs:
```rust
use owo_colors::{OwoColorize, Style};
fn main() {
println!(
"{}",
"bright cyan if this is terminal output"
.if_stdout_tty(|text| text.bright_cyan())
);
// applying multiple at both
println!(
"{}",
"bright cyan AND underlined(?!) if this is terminal output"
.if_stdout_tty(|text| text.style(
Style::new()
.bright_cyan()
.underline()
))
);
}
```

Add ability to conditionally apply styles if stdout/stderr is a tty

---

Cargo.toml
src/colors.rs
src/colors/custom.rs
src/colors/xterm.rs
src/combo.rs
src/lib.rs

This is the start of the work needed for #23. Runtime colors and non-color styling still needs this optimization

Add autoref specialization for compile-time colors

---

Cargo.toml
examples/override.rs
src/lib.rs
src/overrides.rs
src/supports_colors.rs

Closes #33.
Override example included:
```rust
use owo_colors::{OwoColorize, Stream::Stdout};
fn main() {
println!("Override color=always");
owo_colors::set_override(true);
println!("{}", "blue".if_supports_color(Stdout, |text| text.blue()));
println!("Override color=never");
owo_colors::set_override(false);
println!("{}", "green".if_supports_color(Stdout, |text| text.green()));
println!("Override color=auto");
owo_colors::unset_override();
println!(
"{}",
"yellow".if_supports_color(Stdout, |text| text.bright_yellow())
);
}
```

Add support for globally overriding if_supports_color

---

Cargo.toml
src/lib.rs

Also turn it on for docs.rs.
Fixes #38.

only enable doc_cfg when a cfg attribute is passed

---

Cargo.toml
LICENSE

MIT license requires the license text to be included with all derivative
works.
Resolves #52.
Signed-off-by: Michel Alexandre Salim <salimma@fedoraproject.org>

Add license text

---

src/dyn_styles.rs

This allows easily accessing and unstyled version of a `Styled` and allows amending a `Style` later on.

Make `Styled` `target` and `style` public

---

Cargo.toml
src/dyn_styles.rs
src/lib.rs
src/styled_list.rs

Analogous to `ansi_term::ANSIStrings`
Related #55
@jam1garner I haven't found anything better than your second approach, so I went with that, thanks.
Adding an alias for `Vec` requires `alloc`, so I made that an optional feature (disabled by default, given the zero-allocation focus of the library).

Add `StyledList` for printing a list of `Styled` values more efficiently

---

README.md

Previously this was pointed towards v3.4.0 on docs.rs, which is not the current latest version. docs.rs supports using `latest` in the url, and by doing so this link will remain up-to-date for future version bumps.

fix docs link in the readme

---

README.md

Found via `markdownlint *.md --disable MD033`

Resolve Markdown issues in README.md

---

src/lib.rs
src/overrides.rs

This is relatively straightforward without creating an issue first. Still, I hope that is okay, as I did not want to duplicate the information provided in both the issue and PR for such a minor issue/feature. Please be free to close this PR if this isn't something that you want this crate to provide or think is inappropriate!
---
During the development of [error-stack](https://lib.rs/crates/error-stack) 0.3, I wanted to temporarily disable the colored output without impacting the previous set configuration. This is currently impossible because one cannot check the current overwrite value. Instead of increasing the API surface by introducing a new function that checks the current overwrite, instead, a new function is added: `with_override`, which complements `set_override` and …

overwrite color support temporarily during function execution

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
src/overrides.rs
src/supports_colors.rs

Also deprecate supports-color v1 to the greatest extent possible.
Fixes https://github.com/jam1garner/owo-colors/issues/114.

Add a way to support both v1 and v2 of supports-colors

---

src/lib.rs

This PR fixes a small typo where `BgColorDisplay` was accidentally spelled as 'BgCBgColorDisplay'.

Fix typo in `Color` trait documentation

---

.github/workflows/ci.yml
Cargo.toml
README.md

The `banners` example already requires Rust 1.55 to build. Going one version further to 1.56 silences the (harmless) warning about the `rust-version` key in the Cargo.toml being unsupported and unlocks Rust 2021.
The example could instead be fixed to build with Rust 1.51, but don't bother and just bump the MSRV since 1.56 is already one and a half years old at this point.
---
Note: This will need to be rebased once https://github.com/jam1garner/owo-colors/pull/101 landed to get CI green.

Raise MSRV to 1.56

---

src/lib.rs

CI is currently broken by clippy warnings on 1.70.0-nightly. Fix them.
```
warning: the following explicit lifetimes could be elided: 'a
--> src/lib.rs:192:13
|
192 |               fn $fg_method<'a>(&'a self) -> FgColorDisplay<'a, colors::$color, Self> {
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
287 | /     color_methods! {
288 | |         /// Change the foreground color to black
289 | |         /// Change the background color to black
290 | |         Black    black    on_black,
...   |
346 | |         BrightWhite    bright_white    on_bright_white,
347 | |     }
| |_____- in this macro invocation
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: …
```

Elide explicit lifetime annotations

---

src/combo.rs
src/dyn_styles.rs
src/lib.rs

I was reading through the documentation and noticed that the doc comment for [underline](https://docs.rs/owo-colors/3.5.0/owo_colors/struct.Style.html#method.underline) incorrectly said "italicized". 
Since I decided to make a PR to fix the docs, I figured that I should run the [typos](https://crates.io/crates/typos) crate while I'm here and fix any typos that it found.

Fix typos in documentation and test code

---

src/combo.rs
src/lib.rs

This fixes a couple `clippy` warnings ("needless `fn main` in doctest") and a bunch of `doc` warnings ("redundant link target").

Fix `clippy` and `doc` warnings

---

src/colors/custom.rs

The current code relies on const promotion happening; I *believe* that is unsound here; I'm not 100% sure, it's possible that in a const context `&rgb_to_ansi(..)` guarantees const promotion of the result into a `&'static [u8]`.
Either way, no unsafe code > having unsafe code.
Seems relevant: https://github.com/rust-lang/const-eval/blob/master/promotion.md#enclosing-scope-rule

Replace brittle const-promotion-based unsafe code with safe code

---

examples/const_colors.rs
src/colors.rs
src/combo.rs
src/dyn_styles.rs
src/lib.rs
src/styles.rs

Since owo-colors does most of its work via the type system, it makes sense for it to be possible to construct the types at compile time. I've rewritten a few methods to make them const friendly (no &mut refs...), but otherwise this appears to work great.
One change I've made is to drop the `Sized` requirement on the types that are only accessed via pointer indirection. This allows users to write types like `FgColorDisplay<Green, str>` which feels great. I can't drop the `Sized` requirement on `OwoColorize` due to API compat, though, sadly.
Whatever bits are left out are not possible to convert over to const currently -- I've added comments explaining why. But enough of the API is available (including dynamic styles!) that I think most user needs will be met through this.
Closes #62.

Make most of the API const-friendly

---

src/lib.rs
src/supports_colors.rs

`supports_colors` is a private module, `Stream` is a no-inline reexport. As a result, docs.rs does not render any sort of documentation about what `Stream` is. I'm tentatively removing `doc(no_inline)` as I think this is the right fix.

Render `Stream` docs

---

src/colors.rs
src/colors/css.rs
src/colors/custom.rs
src/colors/dynamic.rs
src/colors/xterm.rs
src/dyn_colors.rs
src/lib.rs

These were already effectively sealed via the doc(hidden) methods, but we should also mark it so.

explicitly mark Color and DynColor sealed
